### ISSUE TITLE
Only using CPU?

### ISSUE THREAD

**Issue by rlimaservinfo** [LeonLok/Deep-SORT-YOLOv4#1]
Hi I am testing you project and everything seems to work fine.
My question is that I only see CPU usage (around 75%) and almost nothing GPU (4%) is that correct?
My HW
Ubuntu 20.04
Intel i5
Nvidia GTX 2060 8 GB

Only get 1 FPS

Thanks in advance

**Comment by LeonLok** [comment]
Do you have tensorflow-gpu installed in your environment? I'm using tensorflow-gpu 1.14 and the CPU usage is never that high.
