### ISSUE TITLE
Generating anchors my custom keras model

### ISSUE THREAD

**Issue by vihari1729** [LeonLok/Deep-SORT-YOLOv4#10]
When I am running yolo.py for tracking with my custom keras model, I am getting following error:

 ```
main(YOLO())
  File "/home/unizen/Deep-SORT-YOLOv4/tensorflow1.14/yolo.py", line 30, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/unizen/Deep-SORT-YOLOv4/tensorflow1.14/yolo.py", line 51, in generate
    self.yolo_model = load_model(model_path, custom_objects={'Mish': Mish}, compile=False)
  File "/home/unizen/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/unizen/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "/home/unizen/anaconda3/lib/python3.7/site-packages/keras/utils/io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

```

This might be due to the different yolo_anchors.txt for my model. Do you have any idea of generating anchors for custom yolo model

**Comment by LeonLok** [comment]
Why do you think it's the anchors causing the issue? Have you checked your other settings in `yolo.py`?

**Comment by vihari1729** [comment]
@LeonLok   I have trained my dataset using this git hub repository https://github.com/AntonMu/TrainYourOwnYOLO. Here I tried the inference part and is working fine for both the images and videos input. Then I started using this github repository https://github.com/Qidian213/deep_sort_yolov3 for tracking, where the files are almost similar to yours but for yolov3 model. Here, while running yolo.py I changed the paths of both classes and model to my trained files and what objects to track in demo.py as mentioned in  readme.md in your repository. still I am getting above error.

My Question is should I just stick to yolov3 anchors.txt or should I generate own anchors for my pretrained keras model

**Comment by LeonLok** [comment]
You should use the same anchors that you used when you trained your model. As for whether or not you should generate your own - that depends on if you want better performance when detecting your classes. 

Again, have you checked your other settings in `yolo.py` like image size etc.?

**Comment by vihari1729** [comment]
@LeonLok All my Images are of size (650, 354) and changed the image size from (416, 416) to (650, 354) in yolo.py. still I am getting the same error as above. no change

But my question, Do Image size really matter?. what if we train the model with different image sizes?. I think there should be something else to change

**Comment by vihari1729** [comment]
@LeonLok  In the yolo.py, they fixed the image size and further defined the code according to it. But, How would i achieve the tracking for the custom yolo-keras model 

waiting for your response

**Comment by LeonLok** [comment]
> 
> 
> @LeonLok All my Images are of size (650, 354) and changed the image size from (416, 416) to (650, 354) in yolo.py. still I am getting the same error as above. no change
> 
> But my question, Do Image size really matter?. what if we train the model with different image sizes?. I think there should be something else to change

It needs to be the same as your **model image size** that you used when you trained your model.  If this is not the same then it won't work.

For tracking, see https://github.com/nwojke/cosine_metric_learning. YOLO is used for object detection, not object tracking.

**Comment by vihari1729** [comment]
@LeonLok  The Image size is (416,416) and used same yolo_anchors.txt as of yolo3.h5 for training. The error is difficult to understand. 

For training the Images from scratch, DO I need to follow the https://github.com/Ma-Dan/keras-yolo4 or https://github.com/AlexeyAB/darknet.  So that I can use yolo.py and demo.py from your repository for tracking.

Kindly help me

**Comment by LeonLok** [comment]
Why are you using a YOLO v3 model? This repository is for YOLO v4. I don't understand what you are trying to do.

**Comment by vihari1729** [comment]
No. I just want to train my dataset to get keras custom model from yolov4 model

**Comment by LeonLok** [comment]
Then you need to use Darknet to train a YOLO v4 model and then use `convert.py` to convert the weights into Keras format. Make sure `yolo.py` has the same config settings as when you trained the model and it should work.

**Comment by LeonLok** [comment]
If you don't want to use Darknet, then you can use `train.py` from Ma-Dan's repository.

**Comment by vihari1729** [comment]
@LeonLok Thanks bro. I understood your point.
