### ISSUE TITLE
Unable to track with custom keras model

### ISSUE THREAD

**Issue by vihari1729** [LeonLok/Deep-SORT-YOLOv4#13]
@LeonLok 
 Hi,
 Since, I am getting error when I am converting yolo custom model(trained with my dataset) to keras model like this:
```
File "convert.py", line 173, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 157, in __init__
    self.load_yolo()
  File "convert.py", line 98, in load_yolo
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```
I tried converting using this code:
https://github.com/Runist/YOLOv4/blob/master/utils/convert.py

It is successful, But I am unable to track with that  keras-model when I am using demo.py .

If you don't mind, Could you go through the both codes and check where it is wrong

**Comment by LeonLok** [comment]
YOLO is for object detection, not tracking.

Make sure this contains your class: https://github.com/LeonLok/Deep-SORT-YOLOv4/blob/695ef5d20a22c91252e4b6dffbbb9a9511ae2a93/tensorflow1.14/deep-sort-yolov4/yolo.py#L103
