### ISSUE TITLE
Works very slow

### ISSUE THREAD

**Issue by Arhanel** [LeonLok/Deep-SORT-YOLOv4#19]
Hey I was testing your code and its weird but it seems to run with half of the speed of other implementation witch uses YOLOv3 with tensorflow. I don't know if I am doing something wrong but YOLOv3 manages to run 1.4FPS on CPU and 7FPS on GPU but this implementation runs around 0.6FPS on CPU and 3 FPS on GPU. I value boost in accuracy but damn, it works so slow.

**Comment by Senwang98** [comment]
I run this code 10FPS on 1060.(1280*720 video)

**Comment by Arhanel** [comment]
I tested it on GTX 950 and had 3-4 FPS, video was I think FHD. Same setting and same video but yolov3 was running with 7-8 FPS so i don't know

**Comment by ibrandiay** [comment]
even for me too it's slow. yolov3 is faster
